colorscheme base16-gord

add-highlighter global/ number_lines -relative -hlcursor
add-highlighter global/ show_matching
# add-highlighter global/ wrap

set global ui_options ncurses_assistant=none
set global modelinefmt '%val{bufname} %val{cursor_line}:%val{cursor_char_column} {{context_info}} {{mode_info}}'
