colorscheme base16-gord

add-highlighter global/ number-lines -relative -hlcursor
add-highlighter global/ show-matching
add-highlighter global/ wrap
add-highlighter global/ column 80 default,rgb:2D2D2D

set global ui_options ncurses_assistant=none
set global modelinefmt '%val{bufname} %val{cursor_line}:%val{cursor_char_column} {{context_info}} {{mode_info}}'
